# Generated by Django 2.2 on 2020-03-19 07:03

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200318_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field=models.IntegerField(default=0), null=True, upload_to=posts.models.upload, width_field=models.IntegerField(default=0)),
        ),
    ]
